import '@/styles/globals.css'
import { fontSans } from '@/lib/font'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={fontSans.className}>{children}</body>
    </html>
  )
}
