import '@/styles/globals.css'

import { fontSans } from '@/lib/fonts'
import { cn } from '@/utils/style-utils'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={cn(fontSans.variable)}>
      <body>{children}</body>
    </html>
  )
}
